name: delaycfg

parameters:
  n_steps: 32
  cfg_scale: 2.3
  init_nsteps: 12
  sigma_gibbs: 2.0
  n_gibbs: 2
  cfg_scale_init: 1.0  # by default, no cfg in the init
  delta: 0.1

context_parameters:
    # audio exp
    audioldm2-large:
      n_steps: 200
